name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update API Gateway URL
      run: |
        API_URL=$(aws cloudformation describe-stacks --stack-name VisitorCounterCdkStack --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
        sed -i "s|REPLACE_WITH_API_GATEWAY_URL|$API_URL|g" js/main.js

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete --exclude ".git/*" --exclude ".github/*"

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"